#!/usr/bin/env ruby

input = open('.triggertest', 'r+')

commands = { 'spec' => 'rspec', 'features' => 'cucumber' }
fname = linenum = command = nil

loop do
  args = input.gets
  matched = args.match /^(spec|features)\// 
  if matched
    unless args =~ /step_definitions/
      fname, linenum = args.split
      command = commands[matched[1]]
    end
  end

  if fname
    cmd = "bundle exec #{command} #{fname} -l #{linenum}"
    puts cmd
    system cmd
  end
end
